### ISSUE TITLE
[UPDATE] Drop TCPB Server

### ISSUE THREAD

**Issue by coltonbh** [mtzgroup/chemcloud-server#64]
TCPB server is unstable, crashes frequently, has returned mistaken energy calculations for 3+ years, and is the cause of 98%+ of the errors returned to end users (as seen via Ethan's project). Using the server also greatly complicates the deploy process as I need to manage and scale a separate server process and an nginx frontend to access underlying files. Since the server doesn't properly communicate its ready status, after crashes docker restarts it, it communicates "ready" before it actually is ready, and this can cause cascading failures in computations that would otherwise succeed. In sum, the server is poorly implemented and has required tons of awkwardness to accommodate its flaws. It's not built to scale and requires constant babysitting by a human.

I'd like to drop it in favor or running terachem from the command line. Annoyingly I'll need to parse results from the tc.out file, but this should be orders of magnitude more stable than the current server. Need to develop a `tcparse` library, put it into `qcengine`, and then update the backend workers to build with terachem.

This will result in an exponentially more stable system with far fewer issues for end users and dramatically simpler scaling on the backend.

Work on this after publishing paper...

**Comment by danielhollas** [comment]
Hi @coltonbh. I am now considering using TeraChem in server mode and this issue made me worried. :-) I believe one reason for the server mode was the the GPU initialization is very slow, so for small/medium molecules a significant part of the overall wall time is spent in init. I wonder how that plays out in your context.

**Comment by coltonbh** [comment]
You are correct that the startup time was a primary motivator for server mode and it does save the startup time for subsequent calculations. This saves somewhere on the order of 1-3 seconds per calculation. This can be significant for MD runs on small molecules. 

If you are running just one server and are content to constantly monitor it for crashes, then handle manually restarting it, and can accept that your code calling the server may crash anytime the server crashes, then server mode may work just fine for you. The real problem for me arises when I want to develop and scale software that uses server mode in a highly reliable fashion. The server is not correctly implemented to run as a dependable service that external software can rely upon.

The wins are amortized startup time and structured data. If you use the tcpb-client python package you can speak MOLSSI standardized data structures to TeraChem which allows interoperability between packages and provides you a really nice output data structure you can use in subsequent analysis. 

Using docker to run your terachem server can help aleviate the server crashing issue. 

Both tcpb-client and docker containers are publically available and have decent documentation. Any questions let me know. 

https://hub.docker.com/r/mtzgroup/terachem

https://hub.docker.com/r/mtzgroup/terachem-frontend

https://github.com/mtzgroup/tcpb-client

**Comment by danielhollas** [comment]
@coltonbh thank you so much for a detailed writeup, very helpful. I've been able to play around a little bit and make stuff work, both in the container and with locally built terachem. 

One thing that I am unsure about is what is the purpose of the `mtzgroup/terachem-frontend` Docker image. What problem does it solve?

**Comment by coltonbh** [comment]
It gives you access to all the files the terachem server writes. The priticol buffer interface sends over structured data. The frontend serves files, like the wave function (and all other files)

**Comment by coltonbh** [comment]
Removed `tcpb` with the update to `qcio`.
